version: "3.8"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: surco
      POSTGRES_PASSWORD: surco
      POSTGRES_DB: surco
    ports:
      - "5432:5432"
    volumes:
      - surco_db_data:/var/lib/postgresql/data

volumes:
  surco_db_data:
